development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  host: localhost
  port: 3306
  database: ReactTest
  username: root
  password: password
  pool: 5


production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  host: localhost
  port: 3306
  database: ReactTest
  username: root
  password: password
  pool: 5
